# Simulation of Life Configuration
# This plugin is a simulation of life

# General settings
general:
  # Enable or disable the plugin
  enabled: true
  # Debug mode for logging
  debug: true
  # Send player messages of their activity
  player-notifications: false
  # Send admin messages for commands (you shouldn't set this to false :) )
  admin-notifications: true

# Exhaustion settings
exhaustion:
  # Amount of exhaustion when placing a block (4 = 1 hunger or saturation)
  place-block: 1.0
  # Amount of exhaustion when destroying a block (4 = 1 hunger or saturation)
  mining-block: 1.0
  # Amount of exhaustion when farming a block (4 = 1 hunger or saturation)
  farming-block: 1.0
  # Amount of exhaustion when hitting entities (4 = 1 hunger or saturation)
  hit-entity: 1.0
  # Amount of exhaustion when doing a default action (4 = 1 hunger or saturation)
  default: 1.0
  # Minimum food level before reducing (prevents starvation if above 1)
  minimum-food-level: 0.0
  # Cooldown between exhaustion in milliseconds (0 = no cooldown)
  cooldown: 100

# Specialization settings
specialization:
  # Amount of points to gain when mining
  mining: 1
  # Amount of points to gain when farming
  farming: 1
  # Amount of points to gain when building
  building: 1
  # Amount of points to gain when fighting
  fighting: 1
  # Amount of points to gain when being athletic
  athletics: 1  
  # Maximum points a player can have
  max-points: 1000
  # Auto-save interval in minutes (0 = disabled, only save on server shutdown)
  auto-save-interval: 10

# Run speed settings
run-speed:
  # Base run speed when sprinting
  base-speed: 0.25
  # Maximum run speed (minecraft max sprint speed is 1.0, going beyond will break it)
  max-speed: 0.9

# Block-specific settings
blocks:
  # Blocks that don't cause exhaustion when placed
  place-exempt:
    - AIR
    - CAVE_AIR
    - VOID_AIR
  # Blocks that don't cause exhaustion when destroyed
  destroy-exempt:
    - AIR
    - CAVE_AIR
    - VOID_AIR

# Notifications
admin-notification-messages:
  prefix: "<dark_gray>[<red>Simulation of Life</red>]</dark_gray> "
  exhaustion-reduced: "<yellow>Exhaustion: <red>{exhaustion}</red>/<green>4</green></yellow>"
  plugin-reloaded: "<green>Plugin configuration reloaded!</green>"
  plugin-status: "<green>Plugin is <dark_green>enabled</dark_green>"
  plugin-disabled: "<red>Plugin is <dark_red>disabled</dark_red></red>" 