name: SimulationOfLife
version: '0.6.4'
main: com.binkibonk.simulationoflife.SimulationOfLife
api-version: '1.21'
authors: [Binkibonk]
description: Simulating the growth and fall of civilizations
folia-supported: true
website: https://github.com/GabrielCirciu/SimulationOfLife

commands:
  simulationoflife:
    description: Main commands for Simulation of Life
    usage: /simulationoflife [stats|status|perf|debug|spec-all|spec-set|spec-reset|spec-reset-all|save|reload]

permissions:
  simulationoflife.admin:
    description: Allows access to admin commands
    default: op
  simulationoflife.player:
    description: Allows access to player commands
    default: true
  simulationoflife.bypass:
    description: Bypass the Simulation
    default: false 