name: SimulationOfLife
version: '0.6.0'
main: com.binkibonk.simulationoflife.SimulationOfLife
api-version: '1.21'
authors: [Binkibonk]
description: Simulating the growth and fall of civilizations
folia-supported: true
website: https://github.com/binkibonk/simulation-of-life

commands:
  simulationoflife:
    description: Main command for SimulationOfLife plugin
    usage: /simulationoflife [reload|status|perf|debug|specs|stats]

permissions:
  simulationoflife.admin:
    description: Allows access to admin commands
    default: op
  simulationoflife.player:
    description: Allows access to player commands
    default: true
  simulationoflife.bypass:
    description: Bypass the Simulation
    default: false 